[package]
name = "esp-ds"
version = "0.1.0"
edition = "2024"

[dependencies]
rsa = { version = "0.9", features = ["pem"] }
aes = "0.8"
cbc = "0.1"
sha2 = "0.10"
hmac = "0.12"
bincode = "2.0"
clap = { version = "4.5", features = ["derive"] }
pem = "3.0"
x509-parser = "0.16"
rand = "0.8"
num-traits = "0.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
